project_id = "lxdjtwxumzsyowdkahrt"

[functions.grid-load-balancer]
verify_jwt = false

[functions.check-gtv-exceedance]
verify_jwt = false

[functions.ocpp-handler]
verify_jwt = false

[functions.ocpp-ws]
verify_jwt = false

[functions.ocpp-ingest]
verify_jwt = false

[functions.smartstuff-ingest]
verify_jwt = false

[functions.check-webhook-health]
verify_jwt = false

[functions.shelly-ingest]
verify_jwt = false

[functions.shelly-ws]
verify_jwt = false

[functions.evaluate-meter-models]
verify_jwt = false

[functions.analyze-firmware]
verify_jwt = false

[functions.check-eflux-connection]
verify_jwt = false