import type { ECCLogEntry, ECCOcppMessage, ECCConfigRow, ECCState } from './ecc-types';

export const DEFAULT_STATE: ECCState = {
  connected: false,
  ocppConnected: false,
  device: {
    id: 'NLQWCE5M8WM2',
    serial: '11761346',
    model: 'EVC2.2',
    vendor: 'LMS',
    fw: 'EVC4V32R18P3',
    hw: '4.x',
  },
  connectors: [
    { id: 1, status: 'Faulted', errorCode: 'PowerMeterFailure', cpState: 'F', current: 16, energy: 0, profile: 0 },
    { id: 2, status: 'Faulted', errorCode: 'ReaderFailure', cpState: 'F', current: 16, energy: 0, profile: 0 },
  ],
  gsm: { signal: 21, ip: '10.109.129.193', apn: 'simpoint.m2m' },
  logEntries: [],
  ocppMessages: [],
  cfgData: [],
};

export const DEMO_LOG: Omit<ECCLogEntry, 'id'>[] = [
  { time: '20:07:33', msg: 'Protocol [CH][TYPE]:[1:GSM][2:OCPP1.6]', type: 'info' },
  { time: '20:07:33', msg: 'OCPP ID [NLQWCE5M8WM2]', type: 'info' },
  { time: '20:07:33', msg: 'Model Name [EVC2.2] Vendor [LMS]', type: 'info' },
  { time: '20:07:33', msg: 'Chargepoint serial [11761346]', type: 'info' },
  { time: '20:07:33', msg: 'Meter0:SN[230873974]Type[23]Speed[9600]Addr[1]', type: 'info' },
  { time: '20:07:33', msg: 'DEST:[/#SN#],[ocpp.qwello.eu:80]', type: 'info' },
  { time: '20:07:33', msg: 'MODULES:[OCPP,ETH]', type: 'info' },
  { time: '20:07:39', msg: 'GSM MUX start', type: 'gsm' },
  { time: '20:07:39', msg: 'GSM RST CAUSE:[REGULAR][GSMNOK][SIM NOT CHECKED YET]', type: 'warn' },
  { time: '20:07:40', msg: 'GSM PWR ON', type: 'gsm' },
  { time: '20:07:44', msg: 'WF(AT->OK)-->[ATOK]', type: 'gsm' },
  { time: '20:07:45', msg: 'WF(AT+CPIN?->+CPIN: READY)', type: 'gsm' },
  { time: '20:07:48', msg: 'GSM Modem: BG95-M3', type: 'gsm' },
  { time: '20:07:49', msg: 'GSM IMEI[861059065127536]', type: 'info' },
  { time: '20:07:51', msg: 'GSM CCID[8931084725025260281]', type: 'info' },
  { time: '20:08:00', msg: 'GSM NETWORK_REGISTRATION DONE', type: 'ok' },
  { time: '20:08:02', msg: 'GSM IP Init [simpoint.m2m]', type: 'gsm' },
  { time: '20:08:05', msg: 'APN OK [simpoint.m2m]', type: 'ok' },
  { time: '20:08:06', msg: 'IP:10.109.129.193', type: 'ok' },
  { time: '20:08:07', msg: 'WS CONNECTING [GET /11761346 HTTP/1.1 Host: ocpp.qwello.eu:80]', type: 'ocpp' },
  { time: '20:08:09', msg: 'WS CONNECTION OK', type: 'ok' },
  { time: '20:08:10', msg: 'CHGFLAGS[0][12000000,12000800][KWH error,RFID][28]', type: 'error' },
  { time: '20:08:10', msg: 'CHGFLAGS[1][0,2000800][KWH error][28]', type: 'error' },
  { time: '20:08:11', msg: 'LEDSTATE CH[0] state[KWH0 error(116)]', type: 'error' },
  { time: '20:08:11', msg: 'OCPP OUTREQ[Boot,134]', type: 'ocpp' },
  { time: '20:08:11', msg: '[2,"13347","BootNotification",{"chargePointVendor":"LMS","chargePointModel":"EVC2.2","firmwareVersion":"4.3x.32.R18.P3"}]', type: 'data' },
  { time: '20:08:20', msg: 'OCPP BOOT OK', type: 'ok' },
  { time: '20:08:21', msg: 'StatusNotification connectorId:0 status:Available', type: 'ocpp' },
  { time: '20:08:24', msg: 'StatusNotification connectorId:1 status:Faulted errorCode:ReaderFailure', type: 'warn' },
  { time: '20:08:28', msg: 'StatusNotification connectorId:2 status:Faulted errorCode:PowerMeterFailure', type: 'warn' },
  { time: '20:13:20', msg: '[2,"13354","Heartbeat",{}]', type: 'ocpp' },
  { time: '20:18:22', msg: '[2,"13355","Heartbeat",{}]', type: 'ocpp' },
  { time: '20:23:25', msg: '[2,"13356","Heartbeat",{}]', type: 'ocpp' },
];

export const DEMO_OCPP_MESSAGES: ECCOcppMessage[] = [
  { dir: 'OUT', action: 'BootNotification', seq: '13347', ts: '20:08:11', type: 'req',
    payload: '{"chargePointVendor":"LMS","chargePointModel":"EVC2.2",\n"chargePointSerialNumber":"11761346","firmwareVersion":"4.3x.32.R18.P3",\n"iccid":"8931084725025260281"}' },
  { dir: 'IN', action: 'BootNotification [Response]', seq: '13347', ts: '20:08:20', type: 'resp',
    payload: '{"currentTime":"2026-03-17T20:08:20.864Z","interval":300,"status":"Accepted"}' },
  { dir: 'IN', action: 'SetChargingProfile', seq: 'bd21aa0a-...', ts: '20:08:20', type: 'req',
    payload: '{"connectorId":1,"csChargingProfiles":{"chargingProfileId":1,"stackLevel":0,\n"chargingProfilePurpose":"TxDefaultProfile","chargingProfileKind":"Absolute",\n"chargingSchedule":{"chargingRateUnit":"A","chargingSchedulePeriod":[{"startPeriod":0,"limit":0.0,"numberPhases":3}]}}}' },
  { dir: 'OUT', action: 'StatusNotification', seq: '13348', ts: '20:08:21', type: 'req',
    payload: '{"connectorId":0,"status":"Available","errorCode":"NoError","timestamp":"2026-03-17T20:07:42Z"}' },
  { dir: 'OUT', action: 'StatusNotification', seq: '13349', ts: '20:08:24', type: 'req',
    payload: '{"connectorId":1,"status":"Faulted","errorCode":"ReaderFailure",\n"info":"M3[0/-112]S[12000800:KWH error,RFID]","timestamp":"2026-03-17T20:08:00Z"}' },
  { dir: 'OUT', action: 'StatusNotification', seq: '13350', ts: '20:08:26', type: 'req',
    payload: '{"connectorId":1,"status":"Faulted","errorCode":"OtherError",\n"info":"MODBUS communication error","timestamp":"2026-03-17T20:08:11Z"}' },
  { dir: 'OUT', action: 'StatusNotification', seq: '13351', ts: '20:08:28', type: 'req',
    payload: '{"connectorId":2,"status":"Faulted","errorCode":"PowerMeterFailure",\n"info":"M3[0/-118]S[2000800:KWH error]","timestamp":"2026-03-17T20:08:10Z"}' },
  { dir: 'OUT', action: 'Heartbeat', seq: '13354', ts: '20:13:20', type: 'req', payload: '{}' },
  { dir: 'IN', action: 'Heartbeat [Response]', seq: '13354', ts: '20:13:21', type: 'resp',
    payload: '{"currentTime":"2026-03-17T20:13:20.000Z"}' },
  { dir: 'OUT', action: 'Heartbeat', seq: '13355', ts: '20:18:22', type: 'req', payload: '{}' },
  { dir: 'OUT', action: 'Heartbeat', seq: '13356', ts: '20:23:25', type: 'req', payload: '{}' },
];

export const DEMO_CONFIG: ECCConfigRow[] = [
  { key: 'HeartbeatInterval', value: '1440', readonly: false },
  { key: 'MeterValueSampleInterval', value: '600', readonly: false },
  { key: 'ConnectionTimeOut', value: '60', readonly: false },
  { key: 'AllowOfflineTxForUnknownId', value: 'false', readonly: false },
  { key: 'AuthorizationCacheEnabled', value: 'false', readonly: false },
  { key: 'AuthorizeRemoteTxRequests', value: 'true', readonly: true },
  { key: 'NumberOfConnectors', value: '2', readonly: true },
  { key: 'ConnectorPhaseRotation', value: '1.RST,2.RST', readonly: false },
  { key: 'WebSocketPingInterval', value: '240', readonly: false },
  { key: 'MaxChargingProfilesInstalled', value: '18', readonly: true },
  { key: 'ChargingScheduleMaxPeriods', value: '96', readonly: true },
  { key: 'ChargingScheduleAllowedChargingRateUnit', value: 'current,power', readonly: true },
  { key: 'gsm_APN', value: 'simpoint.m2m', readonly: false },
  { key: 'gsm_SMS', value: '', readonly: false },
  { key: 'gsm_Oper', value: '20408', readonly: false },
  { key: 'gsm_SigQ', value: '20', readonly: true },
  { key: 'gsm_Options', value: 'noSmsChk=0,AutoApn=1,3G4G=0', readonly: false },
  { key: 'com_ProtCh', value: 'GSM', readonly: false },
  { key: 'com_ProtType', value: 'Lms', readonly: false },
  { key: 'com_AuthTimeOut', value: '60', readonly: false },
  { key: 'com_OCPPID', value: 'NLQWCE5M8WM2', readonly: false },
  { key: 'com_Endpoint', value: 'ocpp.qwello.eu:80/#SN#', readonly: false },
  { key: 'com_Options', value: 'comMaster=0,Events=1,BlockBeforeBoot=0,UseTLS=0', readonly: false },
  { key: 'com_AuthOptions', value: 'chkOnlineAuth=1,StopOnAnyCrd=0,AllowAllCards=0', readonly: false },
  { key: 'chg_RatedCurrent', value: '16,16', readonly: false },
  { key: 'chg_Mode3Current', value: '0,0', readonly: false },
  { key: 'chg_Options', value: 'RestartTransOnBoot=0,ZeRdy=1,CircDbg=0,NoBeep=0', readonly: false },
  { key: 'chg_MinChargingCurrent', value: '10', readonly: false },
  { key: 'chg_StationMaxCurrent', value: '254', readonly: false },
  { key: 'chg_ChannelsEnabled', value: '1,2', readonly: false },
  { key: 'chg_SktType', value: 'Lock+CP+PP,Lock+CP+PP', readonly: false },
  { key: 'chg_Reader1', value: 'sl032,any', readonly: false },
  { key: 'chg_Reader2', value: 'none,any', readonly: false },
  { key: 'chg_io_Input', value: 'RCD2,RCD2', readonly: false },
  { key: 'chg_io_Output', value: 'Charging_Ch1,Charging_Ch2', readonly: false },
  { key: 'grid_Role', value: 'station_ctrl', readonly: false },
  { key: 'grid_CommChannel', value: 'canbus', readonly: false },
  { key: 'grid_InstallationMaxCurrent', value: '0', readonly: false },
  { key: 'eth_cfg', value: 'type=dhcp,ip=0.0.0.0,netmask=0.0.0.0', readonly: false },
  { key: 'com_OCPPInfo', value: 'modelname=EVC2.2,vendorname=LMS,CpSn=11761346', readonly: false },
];
